// Dados de exemplo usados enquanto o Supabase não está configurado
export const SEED_PARTNERS = [
  {
    id: "p1",
    nome: "Rosa Surf Club",
    categoria: "Surf & Esportes",
    cidade: "Praia do Rosa",
    instagram: "@rosasurfclub",
    descricao: "Escola de surf e aluguel de equipamentos",
    pin: "1234",
    qr_token: "qr-p1",
    status: "ativo",
    benefit: "15% de desconto no aluguel de prancha",
    emoji: "🏄",
  },
  {
    id: "p2",
    nome: "Bistrô da Rosa",
    categoria: "Gastronomia",
    cidade: "Praia do Rosa",
    instagram: "@bistrodarosa",
    descricao: "Culinária local com ingredientes frescos",
    pin: "5678",
    qr_token: "qr-p2",
    status: "ativo",
    benefit: "1 drink de boas-vindas por visita",
    emoji: "🍃",
  },
  {
    id: "p3",
    nome: "Garopaba Hostel",
    categoria: "Hospedagem",
    cidade: "Garopaba",
    instagram: "@garopabhostel",
    descricao: "Hostel boutique à beira-mar",
    pin: "9012",
    qr_token: "qr-p3",
    status: "ativo",
    benefit: "10% de desconto na hospedagem",
    emoji: "🌿",
  },
  {
    id: "p4",
    nome: "Ateliê Sal & Terra",
    categoria: "Artesanato",
    cidade: "Imbituba",
    instagram: "@saleterraatelie",
    descricao: "Cerâmica e arte local",
    pin: "3456",
    qr_token: "qr-p4",
    status: "ativo",
    benefit: "Brinde artesanal na primeira visita",
    emoji: "🏺",
  },
  {
    id: "p5",
    nome: "Spa Floresta",
    categoria: "Bem-estar",
    cidade: "Praia do Rosa",
    instagram: "@spafloresta",
    descricao: "Massagens e tratamentos naturais",
    pin: "7890",
    qr_token: "qr-p5",
    status: "ativo",
    benefit: "20% de desconto em qualquer massagem",
    emoji: "🌸",
  },
  {
    id: "p6",
    nome: "Café Névoa",
    categoria: "Gastronomia",
    cidade: "Garopaba",
    instagram: "@cafenovoa",
    descricao: "Café especial e pães artesanais",
    pin: "2468",
    qr_token: "qr-p6",
    status: "ativo",
    benefit: "Café expresso gratuito no pedido",
    emoji: "☕",
  },
];

export const SEED_USER = {
  id: "user-demo",
  nome: "Maria Silva",
  email: "maria@exemplo.com",
  status: "ativo",
  tipo: "digital",
  validade_fim: "2027-08-31",
  codigo: "AURA-2026-0042",
};

export const SEED_REDEMPTIONS: string[] = ["p2"]; // p2 já foi usado
